//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by resource.rc
//
#define IDI_SWCCGDM                     103
#define IDD_ABOUTDLG                    105
#define IDR_MENU                        106
#define IDD_EDITDLG                     107
#define IDD_EXCLUDEDLG                  108
#define IDD_HELPDLG                     109
#define IDB_WEAPON                      113
#define IDB_CREATURE                    114
#define IDB_DEJARIK                     115
#define IDB_DEST0                       116
#define IDB_DEST1                       117
#define IDB_DEST2                       118
#define IDB_DEST3                       119
#define IDB_DEST4                       120
#define IDB_DEST5                       121
#define IDB_DEST6                       122
#define IDB_DEVICE                      123
#define IDB_DROID                       124
#define IDB_EVENT                       126
#define IDB_EXTERIOR                    127
#define IDB_FORCE0                      128
#define IDB_ASTRO                       129
#define IDB_IFORCE1                     130
#define IDB_IFORCE2                     131
#define IDB_IFORCE3                     132
#define IDB_IMMEDIATE                   133
#define IDB_IMPERIAL                    134
#define IDB_INTERIOR                    135
#define IDB_INTERRUPT                   136
#define IDB_LIMITED                     137
#define IDB_LOST                        138
#define IDB_MOBILE                      139
#define IDB_PARKERBROS                  140
#define IDB_DESTPI                      141
#define IDB_PILOT                       142
#define IDB_C1                          143
#define IDB_C2                          144
#define IDB_C3                          145
#define IDB_NA                          146
#define IDB_R1                          147
#define IDB_R2                          148
#define IDB_U1                          149
#define IDB_U2                          150
#define IDB_REBEL                       151
#define IDB_RFORCE1                     152
#define IDB_RFORCE2                     153
#define IDB_RFORCE3                     154
#define IDB_REBELLEADER                 155
#define IDB_SCOMP                       156
#define IDB_SHIP                        157
#define IDB_SYSTEM                      158
#define IDB_UNLIMITED                   159
#define IDB_UORL                        160
#define IDB_UTINNI                      161
#define IDB_VEHICLE                     162
#define IDB_WARRIOR                     163
#define IDB_BLANK                       164
#define IDB_EFFECT                      165
#define IDB_ALIEN                       166
#define IDB_ANH                         167
#define IDB_BLANKROW                    168
#define IDD_SORTDLG                     169
#define IDD_SPLASHDLG                   170
#define IDB_SPLASH                      171
#define IDD_INCLUDEDLG                  171
#define IDD_DECKDLG                     173
#define IDD_INFODLG                     175
#define IDB_HOTH                        177
#define IDR_CARDMENU                    178
#define IDI_INF_WEAPON                  179
#define IDI_INF_ANH                     180
#define IDI_INF_BLANK                   181
#define IDI_INF_USEDLOST                182
#define IDI_INF_C1                      183
#define IDI_INF_C2                      184
#define IDI_INF_C3                      185
#define IDI_INF_CRITTER                 186
#define IDI_INF_DEJARIK                 187
#define IDI_INF_DEP0                    188
#define IDI_INF_DEP1                    189
#define IDI_INF_DEP2                    190
#define IDI_INF_DEP3                    191
#define IDI_INF_DEP4                    192
#define IDI_INF_DEP5                    193
#define IDI_INF_DEP6                    194
#define IDI_INF_DEP7                    195
#define IDI_INF_DEP8                    196
#define IDI_INF_DEP9                    197
#define IDI_INF_DEPX                    198
#define IDI_INF_DEST0                   199
#define IDI_INF_DEST1                   200
#define IDI_INF_DEST2                   201
#define IDI_INF_DEST3                   202
#define IDI_INF_DEST4                   203
#define IDI_INF_DEST5                   204
#define IDI_INF_DEST6                   205
#define IDI_INF_DEST7                   206
#define IDI_INF_DESTX                   207
#define IDI_INF_DEVICE                  208
#define IDI_INF_DROID                   209
#define IDI_INF_EFFECT                  210
#define IDI_INF_EVENT                   211
#define IDI_INF_EXTERIOR                212
#define IDI_INF_FORCE0                  213
#define IDI_INF_FOR0                    214
#define IDI_INF_FOR1                    215
#define IDI_INF_FOR2                    216
#define IDI_INF_FOR3                    217
#define IDI_INF_FOR4                    218
#define IDI_INF_FOR5                    219
#define IDI_INF_FOR6                    220
#define IDI_INF_FOR7                    221
#define IDI_INF_FOR8                    222
#define IDI_INF_FOR9                    223
#define IDI_INF_FORX                    224
#define IDI_INF_HOTH                    225
#define IDI_INF_IFORCE1                 226
#define IDI_INF_IFORCE2                 227
#define IDI_INF_IFORCE3                 228
#define IDI_INF_IMMEDIATE               229
#define IDI_INF_IMPERIAL                230
#define IDI_INF_INTERIOR                231
#define IDI_INF_INTERRUPT               232
#define IDI_INF_PREMIERE                233
#define IDI_INF_LOST                    234
#define IDI_INF_MOBILE                  235
#define IDI_INF_NA                      236
#define IDI_INF_PILOT                   237
#define IDI_INF_R1                      238
#define IDI_INF_R2                      239
#define IDI_INF_ASTRO                   240
#define IDI_INF_REBEL                   241
#define IDI_INF_RFORCE1                 242
#define IDI_INF_RFORCE2                 243
#define IDI_INF_RFORCE3                 244
#define IDI_INF_RL                      245
#define IDI_INF_SCOMP                   246
#define IDI_INF_SHIP                    247
#define IDI_INF_SYSTEM                  248
#define IDI_INF_U1                      249
#define IDI_INF_U2                      250
#define IDI_INF_UNLIMITED               251
#define IDI_INF_USED                    252
#define IDI_INF_UTINNI                  253
#define IDI_INF_VEHICLE                 254
#define IDI_INF_WARRIOR                 255
#define IDI_INF_ALIEN                   256
#define IDI_INF_DESTPI                  257
#define IDB_DEST7                       301
#define IDB_DEPLOY1                     302
#define IDB_DEPLOY2                     303
#define IDB_DEPLOY3                     304
#define IDB_DEPLOY4                     305
#define IDB_DEPLOY5                     306
#define IDB_DEPLOY6                     307
#define IDB_DEPLOY7                     308
#define IDB_DEPLOY8                     309
#define IDB_DEPLOY9                     310
#define IDB_DEPLOYX                     311
#define IDB_DEPLOY0                     312
#define IDB_DESTX                       313
#define IDB_FORFEIT0                    314
#define IDB_FORFEIT1                    315
#define IDB_FORFEIT2                    316
#define IDB_FORFEIT3                    317
#define IDB_FORFEIT4                    318
#define IDB_FORFEIT5                    319
#define IDB_FORFEIT6                    320
#define IDB_FORFEIT7                    321
#define IDB_FORFEIT8                    322
#define IDB_FORFEIT9                    323
#define IDB_FORFEITX                    324
#define IDD_PRICEDLG                    325
#define IDC_EXCLUDELIST                 1000
#define IDC_LEAVE_USED                  1001
#define IDC_HELPEDIT                    1003
#define IDC_EDITATTRIBUTES              1005
#define IDC_EDITNAME                    1006
#define IDC_EDITGAMETEXT                1007
#define IDC_EDITLORE                    1008
#define IDC_SORTSIDE                    1009
#define IDC_SORTSET                     1010
#define IDC_SORTRARITY                  1011
#define IDC_SORTTYPE                    1012
#define IDC_SORTDESTINY                 1013
#define IDC_SORTPOWER                   1014
#define IDC_SORTABILITY                 1015
#define IDC_SORTDEPLOY                  1016
#define IDC_SORTFORFEIT                 1017
#define IDC_SORTLIST                    1019
#define IDC_SORTBACK                    1021
#define IDC_SORTSUBTYPE                 1022
#define IDC_HELPBUTTON                  1022
#define IDC_SORTCLEAR                   1023
#define IDC_DECKCARDS                   1031
#define IDC_DECKDESTINY                 1032
#define IDC_DECKLIST                    1033
#define IDC_INF_LORE                    1035
#define IDC_INF_GT                      1036
#define IDC_INF_DESTINY                 1037
#define IDC_INF_TYPE                    1038
#define IDC_INF_SET                     1039
#define IDC_INF_FORFEIT                 1040
#define IDC_INF_DEPLOY                  1041
#define IDC_INF_SCOMP                   1042
#define IDC_INF_WARRIOR                 1043
#define IDC_INF_PILOT                   1044
#define IDC_INF_ASTRO                   1045
#define IDC_INF_RARITY                  1046
#define IDC_INF_NAME                    1047
#define IDC_INF_TYPELABEL               1048
#define IDC_INF_SETNAME                 1049
#define IDC_INF_PRICE                   1050
#define IDC_INF_POWER                   1051
#define IDC_INF_ABILITY                 1052
#define IDC_INF_SPEED                   1053
#define IDC_PRICE_SOURCE                1054
#define IDC_PRICE_ASOF                  1059
#define IDC_PRICE_EDITSOURCE            1060
#define IDC_PRICE_CARDNAME              1061
#define IDC_PRICE_OLD                   1062
#define IDC_PRICE_NEW                   1063
#define ID_FILE_SAVEAS                  40004
#define ID_FILE_EXIT                    40005
#define ID_HELP_ABOUT                   40006
#define ID_FILE_NEW_LIGHT               40007
#define ID_FILE_NEW_DARK                40008
#define ID_FILE_NEW_ALL                 40009
#define ID_DATAFILES_EXPORT             40010
#define ID_DATAFILES_IMPORT             40011
#define ID_VIEW_EXCLUDE                 40012
#define ID_VIEW_INCLUDE                 40013
#define ID_VIEW_FONT_COMPRESSED         40014
#define ID_VIEW_FONT_BOLD               40015
#define ID_VIEW_ICONS_TYPE              40016
#define ID_VIEW_ICONS_DESTINY           40017
#define ID_VIEW_ICONS_RARITY            40018
#define ID_VIEW_ICONS_SET               40019
#define ID_VIEW_ICONS_EXTRA             40020
#define ID_VIEW_CARDNAMES_COLOR         40021
#define ID_VIEW_CARDNAMES_DARKSHADED    40022
#define ID_SORT_BYNAME                  40023
#define ID_SORT_BYTYPE                  40024
#define ID_SORT_BYRARITY                40025
#define ID_SORT_BYDESTINY               40026
#define ID_SORT_BYCUSTOM                40027
#define ID_SORT_DEFINECUSTOM            40028
#define ID_SORT_BYSIDEFIRST             40034
#define ID_SORT_BYSETSFIRST             40035
#define ID_OPTIONS_IGNOREUNLIMITED      40039
#define ID_VIEW_DECKQUANTITY            40040
#define ID_VIEW_DECKWINDOW              40041
#define ID_VIEW_INFOWINDOW              40042
#define ID__ENTERQTY                    40043
#define ID__EDITCARD                    40044
#define ID__EDITPRICE                   40045
#define ID__EXCLUDE                     40046
#define ID__ZEROQTY                     40047
#define ID__CANCEL                      40048

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        326
#define _APS_NEXT_COMMAND_VALUE         40049
#define _APS_NEXT_CONTROL_VALUE         1065
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
